created category entity and added implementation for necessary functi…
nastasiiaKulinich/book-store pull request #10
Opened 2024-07-18 21:18 UTC by nastasiiaKulinich

…onality

2024-07-20 11:43 UTC, okuzan requested changes

2024-07-20 11:43 UTC, okuzan commented on src/main/java/com/example/bookstore/service/category/impl/CategoryServiceImpl.java
> +                );
extract repeated logic to a private method

2024-07-20 11:43 UTC, okuzan commented on src/main/resources/db/changelog/changes/07-create-books-categories-table.yaml
> +                    references: categories(id)
add empty line at EOF where you see this
![image](https://github.com/user-attachments/assets/5cdb6d50-48e7-4c24-b327-0b823aec5392)

2024-07-21 15:25 UTC, MentorMateAcademy approved these changes

2024-07-21 15:26 UTC, merged