created shopping cart and cart item entities and added implementation…
nastasiiaKulinich/book-store pull request #11
Opened 2024-07-24 11:17 UTC by nastasiiaKulinich

… for necessary functionality

2024-07-25 11:13 UTC, MentorMateAcademy requested changes

2024-07-25 11:13 UTC, MentorMateAcademy commented on src/main/java/com/example/bookstore/config/OpenApiConfig.java
> +                .addSecurityItem(new SecurityRequirement().addList("BearerAuth"));
Strings can save to constants

2024-07-26 07:57 UTC, Elena-Bruyako requested changes
Good job. Let's improve it

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    public CartItemDto updateCartItem(
```suggestion
    public ShoppingCartDto updateCartItem(
```

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/dto/cartitem/CreateCartItemRequestDto.java
> +    @NotNull
```suggestion
```

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/dto/cartitem/UpdateCartItemRequestDto.java
> +    @NotNull
```suggestion
```

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/mapper/ShoppingCartMapper.java
> +            @Mapping(source = "cartItems", target = "cartItems")
```suggestion
```

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/mapper/ShoppingCartMapper.java
> +            @Mapping(source = "cartItems", target = "cartItems")
```suggestion
```

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/model/ShoppingCart.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
```

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +    public CartItemDto updateCartItem(
```suggestion
    public ShoppingCartDto updateCartItem(
```

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = getShoppingCartByUserId(id);
Find book in DB first
Check if book already exists in shop cart. If so -> increase quantity, if no -> add cart item

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        cartItemRepository.delete(cartItem);
Be sure, that cartItem will be removed not only from DB but also from shop cart Set<CartItem> cartItems

2024-07-26 07:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/service/user/impl/UserServiceImpl.java
>          return userMapper.toDto(savedUser);
```suggestion
        userRepository.save(user);
        shoppingCartService.registerNewShoppingCart(user);
        return userMapper.toDto(user);
```

2024-07-30 14:44 UTC, Elena-Bruyako approved these changes

2024-07-30 14:48 UTC, merged